Add svn-dav addon and corresponding postinstall

diff --git a/packaging/debian/postinst b/packaging/debian/postinst
--- a/packaging/debian/postinst
+++ b/packaging/debian/postinst
@@ -14,7 +14,8 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
-CLI="openproject"
+APP_NAME="openproject"
+CLI="${APP_NAME}"
 
 # source debconf library
 . /usr/share/debconf/confmodule
@@ -48,6 +49,33 @@ case "$1" in
     db_get openproject/server/ssl
     if [ "$RET" = "true" ]; then web_protocol="https"; else web_protocol="http"; fi
     ${CLI} run rake setting:set[host_name=${web_hostname},protocol=${web_protocol},sys_api_enabled=1,sys_api_key=${sys_api_key}] 1>/dev/null
+
+    port=$(${CLI} config:get PORT || echo "6000")
+
+    # setup SVN integration
+    db_get ${APP_NAME}/svn-dav/autoinstall || true
+    if [ "$RET" = "true" ]; then
+      db_get ${APP_NAME}/svn-dav/repositories || true
+      svn_repositories="$RET"
+
+      cp -f "/opt/${APP_NAME}/extra/svn/OpenProjectAuthentication.pm" /usr/lib/perl5/Apache/
+      echo "PerlLoadModule Apache::OpenProjectAuthentication" > "/etc/${APP_NAME}/apache2/svn-perl.conf"
+
+      src="/usr/share/${APP_NAME}-svn-dav/templates/includes/vhost/svn.conf"
+      dst="/etc/${APP_NAME}/apache2/vhost/svn.conf"
+      if [ -f "$src" ]; then
+	tmpfile=$(mktemp)
+	cp -f "$src" "$tmpfile"
+	sed -i "s|_SVN_REPOSITORIES_|${svn_repositories}|g" ${tmpfile}
+	sed -i "s|_APP_URI_|http://127.0.0.1:${port}|g" ${tmpfile}
+	sed -i "s|_APP_API_KEY_|${sys_api_key}|g" ${tmpfile}
+	mv -f "$tmpfile" "$dst"
+	chmod 0640 "$dst"
+      else
+	echo "Can't find the SVN vhost configuration. Please ensure that the svn-dav addon is installed."
+      fi
+      service apache2 reload || true
+    fi
 
     # scale
     ${CLI} scale web=1 worker=1 || true
